name: ci
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2.2.4
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: pnpm
      - run: cp .env.example .env.development
      - run: pnpm install --frozen-lockfile
      - run: pnpm lint
      - run: pnpm check
